version: "3.9"

services:
  backend:
    build:
      context: ./rosterloop
      dockerfile: Dockerfile
    image: rosterloop-backend:latest
    container_name: rosterloop_backend
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE:-dev}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD:-admin}
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME:-}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD:-}
    depends_on:
      - frontend
    ports:
      - "9092:9092"
    restart: unless-stopped
    networks:
      - football_football-network

  frontend:
    image: rosterloop-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://192.168.178.36:9092/rosterloop/api}
    container_name: rosterloop_frontend
    ports:
      - "3002:3000"
    restart: unless-stopped
    networks:
      - football_football-network

networks:
  football_football-network:
    external: true
